### ISSUE TITLE
Running `npm install` causes an exception

### ISSUE THREAD

**Issue by brennanMKE** [fastlane/fastlane.tools#4]
It appears that a preinstall routine for one of the dependencies fails.

Running `[sudo] npm install -g phantomjs` allowed the build to work. I installed it globally but maybe it is only needed locally. I was expecting `npm install` to handle the installation of all dependencies. Perhaps this process could be improved.

```
npm install
npm WARN package.json fastlanetools@0.1.0 No description
npm WARN package.json fastlanetools@0.1.0 No repository field.
npm WARN package.json fastlanetools@0.1.0 No README data
 
> icomoon-phantomjs@0.4.2 preinstall /Users/brennan/Documents/GitHub/fastlane.tools/node_modules/grunt-fontsmith/node_modules/fontsmith/node_modules/icomoon-phantomjs
> node utils/preinstall.js

Cannot detect PhantomJS version. Please install PhantomJS >= 1.9.0
/Users/brennan/Documents/GitHub/fastlane.tools/node_modules/grunt-fontsmith/node_modules/fontsmith/node_modules/icomoon-phantomjs/utils/preinstall.js:14
    throw err;
          ^
Error: Command failed: /bin/sh -c phantomjs --version
/bin/sh: phantomjs: command not found

    at ChildProcess.exithandler (child_process.js:744:12)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1008:16)
    at Socket.<anonymous> (child_process.js:1176:11)
    at Socket.emit (events.js:107:17)
    at Pipe.close (net.js:476:12)
npm ERR! Darwin 14.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! icomoon-phantomjs@0.4.2 preinstall: `node utils/preinstall.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the icomoon-phantomjs@0.4.2 preinstall script 'node utils/preinstall.js'.
npm ERR! This is most likely a problem with the icomoon-phantomjs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node utils/preinstall.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls icomoon-phantomjs
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/brennan/Documents/GitHub/fastlane.tools/npm-debug.log
```

**Comment by AaronJiwa** [comment]
Hi, the site doesn't actually use fontsmith, so I've removed it, pull it down again it should be fine.

**Comment by KrauseFx** [comment]
Thanks @AaronJiwa :+1:
